export const categoryIcons = [
  { categoryLabel: "Design", categoryIcon: "bi bi-palette" },
  { categoryLabel: "Web Development", categoryIcon: "bi bi-code" },
  { categoryLabel: "Programming", categoryIcon: "bi bi-terminal" },
  { categoryLabel: "Settings/Configuration", categoryIcon: "bi bi-gear" },
  {
    categoryLabel: "Management/Project Management",
    categoryIcon: "bi bi-diagram-3",
  },
  { categoryLabel: "Translation", categoryIcon: "bi bi-translate" },
  { categoryLabel: "Marketing/Analytics", categoryIcon: "bi bi-graph-up" },
  { categoryLabel: "Team/Collaboration", categoryIcon: "bi bi-people" },
  { categoryLabel: "Global/International", categoryIcon: "bi bi-globe" },
  { categoryLabel: "Education/Reading", categoryIcon: "bi bi-book" },
  { categoryLabel: "Scheduling/Events", categoryIcon: "bi bi-calendar" },
  { categoryLabel: "Business/Work", categoryIcon: "bi bi-briefcase" },
  { categoryLabel: "Communication/Support", categoryIcon: "bi bi-chat-dots" },
  { categoryLabel: "Data/Database", categoryIcon: "bi bi-stack" },
  { categoryLabel: "Finance/Budgeting", categoryIcon: "bi bi-wallet" },
  { categoryLabel: "Statistics/Reports", categoryIcon: "bi bi-bar-chart" },
  { categoryLabel: "Cloud Services", categoryIcon: "bi bi-cloud" },
  { categoryLabel: "Social/Community", categoryIcon: "bi bi-emoji-smile" },
  { categoryLabel: "Music/Audio", categoryIcon: "bi bi-music-note" },
  { categoryLabel: "Photography/Media", categoryIcon: "bi bi-camera" },
  { categoryLabel: "Ecommerce/Retail", categoryIcon: "bi bi-shop" },
  { categoryLabel: "Logistics/Delivery", categoryIcon: "bi bi-truck" },
  { categoryLabel: "Writing/Editing", categoryIcon: "bi bi-pencil" },
  { categoryLabel: "Video/Media Production", categoryIcon: "bi bi-film" },
  { categoryLabel: "Technology/IT", categoryIcon: "bi bi-laptop" },
  { categoryLabel: "Ideas/Innovation", categoryIcon: "bi bi-lightbulb" },
  { categoryLabel: "Security/Protection", categoryIcon: "bi bi-shield-lock" },
  { categoryLabel: "Art/Creative Work", categoryIcon: "bi bi-brush" },
  { categoryLabel: "Notifications/Alerts", categoryIcon: "bi bi-bell" },
  {
    categoryLabel: "Documents/File Management",
    categoryIcon: "bi bi-file-earmark",
  },
  { categoryLabel: "Organization/Storage", categoryIcon: "bi bi-folder" },
  { categoryLabel: "Connections/Networking", categoryIcon: "bi bi-link-45deg" },
  { categoryLabel: "Travel/Location", categoryIcon: "bi bi-map" },
  { categoryLabel: "Shopping/Commerce", categoryIcon: "bi bi-cart" },
  { categoryLabel: "Payment/Transactions", categoryIcon: "bi bi-credit-card" },
  { categoryLabel: "Tools/Repair", categoryIcon: "bi bi-wrench" },
  { categoryLabel: "Favorites/Likes", categoryIcon: "bi bi-heart" },
  { categoryLabel: "Featured/Popular", categoryIcon: "bi bi-star" },
  { categoryLabel: "Achievements/Awards", categoryIcon: "bi bi-trophy" },
  { categoryLabel: "Recognition/Certification", categoryIcon: "bi bi-award" },
];
