export const featuresList = [
  "Responsive Design",
  "Custom Backend Development",
  "Frontend Development",
  "CMS Integration",
  "E-commerce Functionality",
  "API Integration",
  "Website Optimization",
  "Security Features",
  "SEO Optimization",
  "Custom Plugin Development",
  "Logo Design",
  "Business Card Design",
  "Social Media Graphics",
  "Flyer/Poster Design",
  "Brochure Design",
  "Branding Packages",
  "Infographic Design",
  "Illustration",
  "Packaging Design",
  "3D Modeling",
  "SEO Services",
  "Social Media Management",
  "Content Creation",
  "Email Marketing",
  "Pay-Per-Click Advertising",
  "Influencer Marketing",
  "Analytics Reporting",
  "Conversion Rate Optimization",
  "Campaign Management",
  "Article Writing",
  "Blog Posts",
  "Copywriting",
  "Proofreading & Editing",
  "Technical Writing",
  "Translation Services",
  "Script Writing",
  "Resume Writing",
  "Ebook Writing",
  "Press Release Writing",
  "Explainer Videos",
  "Promotional Videos",
  "Animation",
  "Video Editing",
  "3D Animation",
  "Whiteboard Animation",
  "Intros & Outros",
  "Visual Effects",
  "Subtitling & Captions",
  "Live Action Explainers",
  "Voice Over",
  "Music Production",
  "Audio Editing",
  "Jingles & Drops",
  "Mixing & Mastering",
  "Podcast Editing",
  "Sound Design",
  "Songwriting",
  "Session Musicians",
  "Audiobook Production",
  "Business Plan Writing",
  "Market Research",
  "Financial Consulting",
  "Business Consulting",
  "Virtual Assistance",
  "Data Entry",
  "Legal Consulting",
  "HR Consulting",
  "Project Management",
  "Customer Service",
  "Fitness Coaching",
  "Life Coaching",
  "Cooking Classes",
  "Astrology & Psychics",
  "Personal Styling",
  "Relationship Advice",
  "Wellness Coaching",
  "Travel Planning",
  "Meditation & Mindfulness",
  "Arts & Crafts Lessons",
];
